/**
 * The MIT License
 *
 * Copyright 2018 Jeffery Shivers.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

import React, { Component } from "react";
import ReactDOM from "react-dom";
import Sweetbot from "./ui/Sweetbot.jsx";
import { error } from "./utils";

/**
 * Create a bot.
 *
 * The user may pass in an empty object (nothing will be rendered) or nothing
 * (new target elements will be generated).
 *
 * @param {Object} [props]
 * @returns {}
 */
const create = props => {
  let targetSelector, target, auto;

  if (props) {
    targetSelector = props.botSelector;
    target = targetSelector ? document.querySelector(targetSelector) : null;
  } else {
    auto = true;
    targetSelector = "...";
    target = document.createElement("div");
    target.classList.add("autogenerated-sweetbot");
    target.id = `autogenerated-sweetbot-${
      document.querySelectorAll(".autogenerated-sweetbot").length
    }`;
    document.body.appendChild(target);
  }

  !targetSelector
    ? error("A bot target selector was not provided")
    : !target
      ? error("Bot container could not be found in document")
      : ReactDOM.render(<Sweetbot customprops={props} auto={auto} />, target);
};

module.exports = { create };
